import React, { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";

export default function Home() {


  return (
   <>
<h1>Home </h1>
<h3>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid eveniet fugiat sapiente eos dignissimos odit facere odio accusantium ullam ut a dolorum, exercitationem obcaecati accusamus deleniti ad iusto sit incidunt, nemo, et laudantium vero! Similique omnis eveniet qui cum? Eius deleniti veritatis rerum rem ipsa soluta animi ducimus, aliquid, suscipit obcaecati iste voluptatum consequuntur cupiditate porro? Debitis commodi maxime tempore aperiam sequi aut, ut enim qui eos atque sunt consequatur veniam, corrupti exercitationem amet? Tempore dicta, fugit accusamus consectetur vero, error, quos perspiciatis provident blanditiis dignissimos repellendus soluta officia debitis fugiat. Ex optio, reiciendis maxime quo ullam vero molestiae deleniti enim. Voluptate, commodi cupiditate. Labore, praesentium, aut ex facilis neque, corrupti nemo unde vero aliquam omnis incidunt blanditiis accusantium obcaecati voluptate ipsum perferendis pariatur et atque cupiditate impedit. Nobis deserunt, labore vitae praesentium corrupti sequi, officia quos, ipsam sint est autem consequuntur voluptates cumque. Quidem natus non ea culpa suscipit qui, iusto commodi voluptates illum, laborum saepe exercitationem fugiat itaque velit ut sed corrupti ipsum illo cupiditate vitae ipsa maiores, alias incidunt earum. Blanditiis ex amet ea obcaecati facere maxime delectus, corrupti nemo culpa necessitatibus quos sit atque eos minima veniam autem vero id dolorem sed adipisci. Nihil, provident. Atque ab saepe quo. Ea, consectetur, eos suscipit magnam placeat illum quibusdam soluta eligendi voluptate dolorem laudantium culpa. Iste quibusdam totam impedit suscipit aspernatur nulla unde ratione architecto dolore rem. Repudiandae aut accusantium debitis impedit voluptate dignissimos modi! Deserunt ut totam praesentium beatae accusamus facilis officiis minus dolores, consequuntur est reiciendis reprehenderit expedita nihil vero similique adipisci eos. Ullam ipsum deleniti deserunt minima modi, a omnis minus totam? Non dolores a totam ipsa velit reprehenderit amet. Laborum veniam ipsam maiores corrupti fugit vero consectetur totam explicabo odio illo atque, placeat culpa? Provident praesentium nam hic, ab magnam esse ipsa architecto debitis!</h3>   </>
  );
}
